### PR TITLE
Fix #536: Fix alignment of icon on RegionSearch

### LINKED ISSUE #536: Fix alignment of icon on `RegionSearch`
The icon is too far to the left

Image

### PR DESCRIPTION
**Pull request by mikelehen**
Before:
image

After:
image

### CODE REVIEW

File: packages/ui-components/src/components/RegionSearch/RegionSearch.tsx [hunk 1]
```diff
@@ -80,6 +80,7 @@ export const RegionSearch = ({
         }
       }}
       clearIcon={<></>}
+      forcePopupIcon={false}
```
Comment (mikelehen) [inline packages/ui-components/src/components/RegionSearch/RegionSearch.tsx:83]: On line 63 we replace the endAdornment with our own icon, but Material-UI normally has its own icons that it adds padding for.  By setting `forcePopupIcon` to false, we tell it not to display those icons and so it doesn't add the padding.  Based on https://stackoverflow.com/a/61258146

**Review by chasulin — APPROVED** [review]
ahhh bless! this was driving me nuts but i hadn't gotten to fixing it myself. 🙏🏼🙏🏼🙏🏼🙏🏼
