### PR TITLE
Several fixes to MetricSeriesChart

### LINKED ISSUE #360: Bugs - MetricSeriesChart
https://www.dropbox.com/scl/fi/ri48yepzt0462ceno0okn/2022-Q4-Hackathon-Notes.paper?dl=0&rlkey=stj3wqol8iipokdngogl6zkpm

- [x] 🐞 `Series` should have `MetricId | Metric` as we do with other components
- [x] 🐞  The y-axis should follow the format of the metrics
- [x] 🐞 `lineProps` should be optional, and receive more props from the SVG path element

### PR DESCRIPTION
**Pull request by pnavarrc**
Close https://github.com/covid-projections/act-now-packages/issues/360

- Update the `Series` interface to take either `Metric` or `MetricId`
- Format the y-axis tick labels on MetricSeriesChart to match the metrics in the series
- Make the `SeriesLine.lineProps` attribute optional

### CODE REVIEW

File: packages/ui-components/src/components/MetricSeriesChart/MetricSeriesChart.tsx [hunk 1]
```diff
@@ -45,9 +46,18 @@ export const MetricSeriesChart = ({
...
   minValue = 0,
 }: MetricSeriesChartProps) => {
+  const metricCatalog = useMetricCatalog();
+
   // Deduplicate the regions and metrics if necessary
   const regions = uniq(series.map(({ region }) => region));
-  const metrics = uniq(series.map(({ metric }) => metric));
+  const metrics = uniq(series.map(({ metric }) => metric)).map((metric) =>
+    metricCatalog.getMetric(metric)
+  );
```
Comment (mikelehen) [inline packages/ui-components/src/components/MetricSeriesChart/MetricSeriesChart.tsx:55]: Not a huge deal, but I think you could trivially combine these 2 maps and it'd be a bit easier to read.

**Review by mikelehen — APPROVED** [review]
Looks good!

File: packages/ui-components/src/components/MetricSeriesChart/MetricSeriesChart.tsx (hunk 1 above)
Comment (pnavarrc) [reply packages/ui-components/src/components/MetricSeriesChart/MetricSeriesChart.tsx:55]: I figured it would be more efficient to call `getMetric` fewer times, but code clarity wins :)

Comment (mikelehen) [reply packages/ui-components/src/components/MetricSeriesChart/MetricSeriesChart.tsx:55]: Oh!  I got lost in the parentheses and didn't realize the uniq was being applied before the second map. 🤦  But yeah, I think this is more readable still. 🤷
